apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: primezone-bot
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: primezone-bot
            image: gcr.io/PROJECT_ID/IMAGE:TAG
            envFrom:
              - secretRef:
                  name: primezone-bot-secret
            resources:
              requests:
                cpu: 100m
              limits:
                cpu: 100m
          restartPolicy: OnFailure